### ISSUE TITLE
Map #kind_of? to #is_a

### ISSUE THREAD

**Issue by postmodern** [DocSpring/ruby_crystal_codemod#4]
Tested ruby_crystal_codemod on one of my older Ruby libraries and noticed it didn't convert `.kind_of?(...)` to `.is_a?(...)`. I would add this myself, but dang is the codebase a bit dense.

**Comment by ndbroadbent** [comment]
Hello, that's a great idea! Yes the codebase is a bit crazy, but I think this shouldn't be too hard if you look at some of the recent commits. Unfortunately I'm not really actively using or maintaining this code, so I won't have any time to work on this, but this is a great idea!
